INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in pokecrystal.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

LampentFrontpic:        INCBIN "gfx/pokemon/lampent/front.animated.2bpp.lz"
GoodraFrontpic:      INCBIN "gfx/pokemon/goodra/front.animated.2bpp.lz"
NinetalesFrontpic:   INCBIN "gfx/pokemon/ninetales/front.animated.2bpp.lz"
SamurottFrontpic:  INCBIN "gfx/pokemon/samurott/front.animated.2bpp.lz"
NidokingFrontpic:    INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
ArticunoFrontpic:      INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"
LitwickFrontpic:       INCBIN "gfx/pokemon/litwick/front.animated.2bpp.lz"
GroudonFrontpic:    INCBIN "gfx/pokemon/groudon/front.animated.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
MetagrossFrontpic:   INCBIN "gfx/pokemon/metagross/front.animated.2bpp.lz"
ZapdosFrontpic:       INCBIN "gfx/pokemon/zapdos/front.animated.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
InfernapeFrontpic:  INCBIN "gfx/pokemon/infernape/front.animated.2bpp.lz"


SECTION "Pics 2", ROMX

FlygonFrontpic:      INCBIN "gfx/pokemon/flygon/front.animated.2bpp.lz"
RapidashFrontpic:    INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
DecidueyeFrontpic:    INCBIN "gfx/pokemon/decidueye/front.animated.2bpp.lz"
NidoqueenFrontpic:   INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
HitmonleeFrontpic:   INCBIN "gfx/pokemon/hitmonlee/front.animated.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
BeedrillFrontpic:    INCBIN "gfx/pokemon/beedrill/front.animated.2bpp.lz"
ArcanineFrontpic:    INCBIN "gfx/pokemon/arcanine/front.animated.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
RayquazaFrontpic:     INCBIN "gfx/pokemon/rayquaza/front.animated.2bpp.lz"
KyogreFrontpic:      INCBIN "gfx/pokemon/kyogre/front.animated.2bpp.lz"
ArbokFrontpic:       INCBIN "gfx/pokemon/arbok/front.animated.2bpp.lz"
GlaceonFrontpic:      INCBIN "gfx/pokemon/glaceon/front.animated.2bpp.lz"
GalvantulaFrontpic:  INCBIN "gfx/pokemon/galvantula/front.animated.2bpp.lz"
SalamenceFrontpic:   INCBIN "gfx/pokemon/salamence/front.animated.2bpp.lz"
MonfernoFrontpic:     INCBIN "gfx/pokemon/monferno/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

SteelixFrontpic:     INCBIN "gfx/pokemon/pancham/front.animated.2bpp.lz"
AlakazamFrontpic:    INCBIN "gfx/pokemon/alakazam/front.animated.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
KangaskhanFrontpic:  INCBIN "gfx/pokemon/kangaskhan/front.animated.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
SimisageFrontpic:    INCBIN "gfx/pokemon/simisage/front.animated.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
StaraptorFrontpic:   INCBIN "gfx/pokemon/staraptor/front.animated.2bpp.lz"
SlowbroFrontpic:     INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
ButterfreeFrontpic:  INCBIN "gfx/pokemon/butterfree/front.animated.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
MiloticFrontpic:     INCBIN "gfx/pokemon/milotic/front.animated.2bpp.lz"
SkarmoryFrontpic:    INCBIN "gfx/pokemon/skarmory/front.animated.2bpp.lz"
DewgongFrontpic:     INCBIN "gfx/pokemon/dewgong/front.animated.2bpp.lz"
LuxioFrontpic:       INCBIN "gfx/pokemon/luxio/front.animated.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
SimisearFrontpic:    INCBIN "gfx/pokemon/simisear/front.animated.2bpp.lz"


SECTION "Pics 4", ROMX

ZangooseFrontpic:    INCBIN "gfx/pokemon/zangoose/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pokemon/hitmontop/front.animated.2bpp.lz"
HawluchaFrontpic:    INCBIN "gfx/pokemon/hawlucha/front.animated.2bpp.lz"
EmolgaFrontpic:     INCBIN "gfx/pokemon/emolga/front.animated.2bpp.lz"
SliggooFrontpic:     INCBIN "gfx/pokemon/sliggoo/front.animated.2bpp.lz"
DragoniteFrontpic:   INCBIN "gfx/pokemon/dragonite/front.animated.2bpp.lz"
PoliwrathFrontpic:   INCBIN "gfx/pokemon/poliwrath/front.animated.2bpp.lz"
ScytherFrontpic:     INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
SylveonFrontpic:  INCBIN "gfx/pokemon/sylveon/front.animated.2bpp.lz"
CameruptFrontpic:     INCBIN "gfx/pokemon/camerupt/front.animated.2bpp.lz"
MukFrontpic:         INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
DewottFrontpic:    INCBIN "gfx/pokemon/dewott/front.animated.2bpp.lz"
ElectriveFrontpic:   INCBIN "gfx/pokemon/electrive/front.animated.2bpp.lz"
NidorinoFrontpic:    INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
SandslashFrontpic:   INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

MightyenaFrontpic:   INCBIN "gfx/pokemon/mightyena/front.animated.2bpp.lz"
MismagiusFrontpic:   INCBIN "gfx/pokemon/mismagius/front.animated.2bpp.lz"
MagnezoneFrontpic:   INCBIN "gfx/pokemon/magnezone/front.animated.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
SimipourFrontpic:    INCBIN "gfx/pokemon/simipour/front.animated.2bpp.lz"
SealeoFrontpic:    INCBIN "gfx/pokemon/sealeo/front.animated.2bpp.lz"
LinooneFrontpic:     INCBIN "gfx/pokemon/linoone/front.animated.2bpp.lz"
GrumpigFrontpic:     INCBIN "gfx/pokemon/grumpig/front.animated.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
ElectabuzzFrontpic:  INCBIN "gfx/pokemon/electabuzz/front.animated.2bpp.lz"
DoubladeFrontpic:     INCBIN "gfx/pokemon/doublade/front.animated.2bpp.lz"
AzurillFrontpic:   INCBIN "gfx/pokemon/azurill/front.animated.2bpp.lz"
AegislashFrontpic:     INCBIN "gfx/pokemon/aegislash/front.animated.2bpp.lz"
ShelgonFrontpic:    INCBIN "gfx/pokemon/shelgon/front.animated.2bpp.lz"
KadabraFrontpic:     INCBIN "gfx/pokemon/kadabra/front.animated.2bpp.lz"
SableyeFrontpic:   INCBIN "gfx/pokemon/sableye/front.animated.2bpp.lz"
GastlyFrontpic:      INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
MedichamFrontpic:    INCBIN "gfx/pokemon/medicham/front.animated.2bpp.lz"
MimikyuFrontpic:      INCBIN "gfx/pokemon/mimikyu/front.animated.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

AurorusFrontpic:     INCBIN "gfx/pokemon/aurorus/front.animated.2bpp.lz"
TrevenantFrontpic:     INCBIN "gfx/pokemon/trevenant/front.animated.2bpp.lz"
VibravaFrontpic:     INCBIN "gfx/pokemon/vibrava/front.animated.2bpp.lz"
LaprasFrontpic:      INCBIN "gfx/pokemon/lapras/front.animated.2bpp.lz"
GolemFrontpic:       INCBIN "gfx/pokemon/golem/front.animated.2bpp.lz"
PoliwhirlFrontpic:   INCBIN "gfx/pokemon/poliwhirl/front.animated.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
NidorinaFrontpic:    INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
VileplumeFrontpic:   INCBIN "gfx/pokemon/vileplume/front.animated.2bpp.lz"
DartrixFrontpic:     INCBIN "gfx/pokemon/dartrix/front.animated.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
TentacruelFrontpic:  INCBIN "gfx/pokemon/tentacruel/front.animated.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.animated.2bpp.lz"
RioluFrontpic:    INCBIN "gfx/pokemon/riolu/front.animated.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
VulpixFrontpic:      INCBIN "gfx/pokemon/vulpix/front.animated.2bpp.lz"
BronzongFrontpic:      INCBIN "gfx/pokemon/bronzong/front.animated.2bpp.lz"
BronzorFrontpic:   INCBIN "gfx/pokemon/bronzor/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
HelioliskFrontpic:   INCBIN "gfx/pokemon/heliolisk/front.animated.2bpp.lz"
MagmortorFrontpic:   INCBIN "gfx/pokemon/magmortor/front.animated.2bpp.lz"
HonedgeFrontpic:     INCBIN "gfx/pokemon/honedge/front.animated.2bpp.lz"
BellossomFrontpic:   INCBIN "gfx/pokemon/bellossom/front.animated.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
WigglytuffFrontpic:  INCBIN "gfx/pokemon/wigglytuff/front.animated.2bpp.lz"
LudicoloFrontpic:       INCBIN "gfx/pokemon/ludicolo/front.animated.2bpp.lz"
WalreinFrontpic:    INCBIN "gfx/pokemon/walrein/front.animated.2bpp.lz"
NoivernFrontpic:     INCBIN "gfx/pokemon/noivern/front.animated.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
GravelerFrontpic:    INCBIN "gfx/pokemon/graveler/front.animated.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
StaraviaFrontpic:    INCBIN "gfx/pokemon/staravia/front.animated.2bpp.lz"
DrilburFrontpic:      INCBIN "gfx/pokemon/drilbur/front.animated.2bpp.lz"
GengarFrontpic:      INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
TyrantrumFrontpic:     INCBIN "gfx/pokemon/tyrantrum/front.animated.2bpp.lz"
ClaydolFrontpic:   INCBIN "gfx/pokemon/claydol/front.animated.2bpp.lz"
DugtrioFrontpic:     INCBIN "gfx/pokemon/dugtrio/front.animated.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
PyroarFrontpic:  INCBIN "gfx/pokemon/pyroar/front.animated.2bpp.lz"
TogeticFrontpic:     INCBIN "gfx/pokemon/togetic/front.animated.2bpp.lz"
KangaskhanBackpic:   INCBIN "gfx/pokemon/kangaskhan/back.2bpp.lz"


SECTION "Pics 8", ROMX

SeelFrontpic:        INCBIN "gfx/pokemon/seel/front.animated.2bpp.lz"
BudewFrontpic:      INCBIN "gfx/pokemon/budew/front.animated.2bpp.lz"
HonchkrowFrontpic:     INCBIN "gfx/pokemon/honchkrow/front.animated.2bpp.lz"
TropiusFrontpic:     INCBIN "gfx/pokemon/tropius/front.animated.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pokemon/pangoro/front.animated.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pokemon/shroomish/front.animated.2bpp.lz"
MiltankFrontpic:     INCBIN "gfx/pokemon/miltank/front.animated.2bpp.lz"
HaunterFrontpic:     INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
LombreFrontpic:    INCBIN "gfx/pokemon/lombre/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
RowletFrontpic:   INCBIN "gfx/pokemon/rowlet/front.animated.2bpp.lz"
NumelFrontpic:     INCBIN "gfx/pokemon/numel/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
AltariaFrontpic:        INCBIN "gfx/pokemon/altaria/front.animated.2bpp.lz"
LeafeonFrontpic:         INCBIN "gfx/pokemon/leafeon/front.animated.2bpp.lz"
DelcattyFrontpic:   INCBIN "gfx/pokemon/delcatty/front.animated.2bpp.lz"
JynxFrontpic:        INCBIN "gfx/pokemon/jynx/front.animated.2bpp.lz"
HelioptileFrontpic:   INCBIN "gfx/pokemon/helioptile/front.animated.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.animated.2bpp.lz"
ExcadrillFrontpic:      INCBIN "gfx/pokemon/excadrill/front.animated.2bpp.lz"
GloomFrontpic:       INCBIN "gfx/pokemon/gloom/front.animated.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
MetangFrontpic:      INCBIN "gfx/pokemon/metang/front.animated.2bpp.lz"
CofagrigusFrontpic:      INCBIN "gfx/pokemon/cofagrigus/front.animated.2bpp.lz"
ChimcharFrontpic:   INCBIN "gfx/pokemon/chimchar/front.animated.2bpp.lz"
HitmonchanFrontpic:  INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"
BanetteFrontpic:    INCBIN "gfx/pokemon/banette/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

EkansFrontpic:       INCBIN "gfx/pokemon/ekans/front.animated.2bpp.lz"
TrumbeakFrontpic:   INCBIN "gfx/pokemon/trumbeak/front.animated.2bpp.lz"
PikachuFrontpic:     INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
WailordFrontpic:      INCBIN "gfx/pokemon/wailmer/front.animated.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
LuxrayFrontpic:      INCBIN "gfx/pokemon/luxray/front.animated.2bpp.lz"
OshawottFrontpic:    INCBIN "gfx/pokemon/oshawott/front.animated.2bpp.lz"
CorsolaFrontpic:     INCBIN "gfx/pokemon/corsola/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
GoomyFrontpic:       INCBIN "gfx/pokemon/goomy/front.animated.2bpp.lz"
RoseliaFrontpic:    INCBIN "gfx/pokemon/roselia/front.animated.2bpp.lz"
ZigzagoonFrontpic:   INCBIN "gfx/pokemon/zigzagoon/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
JoltikFrontpic:      INCBIN "gfx/pokemon/joltik/front.animated.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
BagonFrontpic:       INCBIN "gfx/pokemon/bagon/front.animated.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
NidoranMFrontpic:    INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
MawileFrontpic:     INCBIN "gfx/pokemon/mawile/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
PanpourFrontpic:     INCBIN "gfx/pokemon/panpour/front.animated.2bpp.lz"
SphealFrontpic:    INCBIN "gfx/pokemon/spheal/front.animated.2bpp.lz"
SandshrewFrontpic:   INCBIN "gfx/pokemon/sandshrew/front.animated.2bpp.lz"
NidoranFFrontpic:    INCBIN "gfx/pokemon/nidoran_f/front.animated.2bpp.lz"
StarlyFrontpic:      INCBIN "gfx/pokemon/starly/front.animated.2bpp.lz"
MedichamBackpic:     INCBIN "gfx/pokemon/medicham/back.2bpp.lz"


SECTION "Pics 10", ROMX

MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
PansearFrontpic:     INCBIN "gfx/pokemon/pansear/front.animated.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
LitleoFrontpic:      INCBIN "gfx/pokemon/litleo/front.animated.2bpp.lz"
RhyperiorFrontpic:   INCBIN "gfx/pokemon/rhyperior/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
JigglypuffFrontpic:  INCBIN "gfx/pokemon/jigglypuff/front.animated.2bpp.lz"
MedititeFrontpic:    INCBIN "gfx/pokemon/meditite/front.animated.2bpp.lz"
NidokingBackpic:     INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
PansageFrontpic:     INCBIN "gfx/pokemon/pansage/front.animated.2bpp.lz"
TrapinchFrontpic:    INCBIN "gfx/pokemon/trapinch/front.animated.2bpp.lz"
GoodraBackpic:       INCBIN "gfx/pokemon/goodra/back.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
SpoinkFrontpic:      INCBIN "gfx/pokemon/spoink/front.animated.2bpp.lz"
SableyeBackpic:    INCBIN "gfx/pokemon/sableye/back.2bpp.lz"
RoseradeFrontpic:     INCBIN "gfx/pokemon/roserade/front.animated.2bpp.lz"
TyrogueFrontpic:     INCBIN "gfx/pokemon/tyrogue/front.animated.2bpp.lz"
HariyamaFrontpic:    INCBIN "gfx/pokemon/hariyama/front.animated.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
ButterfreeBackpic:   INCBIN "gfx/pokemon/butterfree/back.2bpp.lz"
PoochyenaFrontpic:   INCBIN "gfx/pokemon/poochyena/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
AlakazamBackpic:     INCBIN "gfx/pokemon/alakazam/back.2bpp.lz"
LucarioFrontpic:       INCBIN "gfx/pokemon/lucario/front.animated.2bpp.lz"
AbraFrontpic:        INCBIN "gfx/pokemon/abra/front.animated.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"
MiloticBackpic:      INCBIN "gfx/pokemon/Milotic/back.2bpp.lz"
PhantumpFrontpic:    INCBIN "gfx/pokemon/phantump/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"


SECTION "Pics 11", ROMX

ZangooseBackpic:     INCBIN "gfx/pokemon/zangoose/back.2bpp.lz"
NoibatFrontpic:      INCBIN "gfx/pokemon/noibat/front.animated.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.animated.2bpp.lz"
GrowlitheFrontpic:   INCBIN "gfx/pokemon/growlithe/front.animated.2bpp.lz"
SlowpokeFrontpic:    INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
SmoochumFrontpic:    INCBIN "gfx/pokemon/smoochum/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
GrumpigBackpic:      INCBIN "gfx/pokemon/grumpig/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
TyruntFrontpic:     INCBIN "gfx/pokemon/tyrunt/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
ShinxFrontpic:       INCBIN "gfx/pokemon/shinx/front.animated.2bpp.lz"
FeebasFrontpic:      INCBIN "gfx/pokemon/feebas/front.animated.2bpp.lz"
TentacoolFrontpic:   INCBIN "gfx/pokemon/tentacool/front.animated.2bpp.lz"
PikipekFrontpic:      INCBIN "gfx/pokemon/pikipek/front.animated.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
NinetalesBackpic:    INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
LudicoloBackpic:        INCBIN "gfx/pokemon/ludicolo/back.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
NoivernBackpic:      INCBIN "gfx/pokemon/noivern/back.2bpp.lz"
SeviperFrontpic:     INCBIN "gfx/pokemon/seviper/front.animated.2bpp.lz"
SamurottBackpic:   INCBIN "gfx/pokemon/samurott/back.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/breloom/front.animated.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
RhyperiorBackpic:    INCBIN "gfx/pokemon/rhyperior/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"


SECTION "Pics 12", ROMX

MetagrossBackpic:    INCBIN "gfx/pokemon/metagross/back.2bpp.lz"
RayquazaBackpic:      INCBIN "gfx/pokemon/rayquaza/back.2bpp.lz"
LombreBackpic:     INCBIN "gfx/pokemon/lombre/back.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
SandslashBackpic:    INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
WailordBackpic:       INCBIN "gfx/pokemon/wailmer/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
NidoranMBackpic:     INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
DrilburBackpic:       INCBIN "gfx/pokemon/drilbur/back.2bpp.lz"
ChimcharBackpic:    INCBIN "gfx/pokemon/chimchar/back.2bpp.lz"
DartrixBackpic:      INCBIN "gfx/pokemon/dartrix/back.2bpp.lz"
OddishFrontpic:      INCBIN "gfx/pokemon/oddish/front.animated.2bpp.lz"
RapidashBackpic:     INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
SeviperBackpic:      INCBIN "gfx/pokemon/seviper/back.2bpp.lz"
MakuhitaFrontpic:      INCBIN "gfx/pokemon/makuhita/front.animated.2bpp.lz"
PansearBackpic:      INCBIN "gfx/pokemon/pansear/back.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
ElectriveBackpic:    INCBIN "gfx/pokemon/electrive/back.2bpp.lz"
MonfernoBackpic:      INCBIN "gfx/pokemon/monferno/back.2bpp.lz"
DewottBackpic:     INCBIN "gfx/pokemon/dewott/back.2bpp.lz"
SandshrewBackpic:    INCBIN "gfx/pokemon/sandshrew/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
FeebasBackpic:       INCBIN "gfx/pokemon/feebas/back.2bpp.lz"
PoochyenaBackpic:    INCBIN "gfx/pokemon/poochyena/back.2bpp.lz"
TeddiursaFrontpic:   INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
GloomBackpic:        INCBIN "gfx/pokemon/gloom/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
BeedrillBackpic:     INCBIN "gfx/pokemon/beedrill/back.2bpp.lz"
ArcanineBackpic:     INCBIN "gfx/pokemon/arcanine/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
NumelBackpic:      INCBIN "gfx/pokemon/numel/back.2bpp.lz"
BeldumFrontpic:      INCBIN "gfx/pokemon/beldum/front.animated.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"


SECTION "Pics 13", ROMX

TyruntBackpic:      INCBIN "gfx/pokemon/tyrunt/back.2bpp.lz"
StarlyBackpic:       INCBIN "gfx/pokemon/starly/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/breloom/back.2bpp.lz"
BronzongBackpic:       INCBIN "gfx/pokemon/bronzong/back.2bpp.lz"
InfernapeBackpic:   INCBIN "gfx/pokemon/infernape/back.2bpp.lz"
ShelgonBackpic:     INCBIN "gfx/pokemon/shelgon/back.2bpp.lz"
NidoqueenBackpic:    INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
ElectabuzzBackpic:   INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
ExcadrillBackpic:       INCBIN "gfx/pokemon/excadrill/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
MiltankBackpic:      INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pokemon/pancham/back.2bpp.lz"
SimipourBackpic:     INCBIN "gfx/pokemon/simipour/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
ToucannonFrontpic:     INCBIN "gfx/pokemon/toucannon/front.animated.2bpp.lz"
PonytaBackpic:       INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
SkittyFrontpic:    INCBIN "gfx/pokemon/skitty/front.animated.2bpp.lz"
PoliwagFrontpic:     INCBIN "gfx/pokemon/poliwag/front.animated.2bpp.lz"
HawluchaBackpic:     INCBIN "gfx/pokemon/hawlucha/back.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
NidorinaBackpic:     INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
TentacruelBackpic:   INCBIN "gfx/pokemon/tentacruel/back.2bpp.lz"
GrowlitheBackpic:    INCBIN "gfx/pokemon/growlithe/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
SliggooBackpic:      INCBIN "gfx/pokemon/sliggoo/back.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
PoliwrathBackpic:    INCBIN "gfx/pokemon/poliwrath/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
LotadFrontpic:     INCBIN "gfx/pokemon/lotad/front.animated.2bpp.lz"
NidorinoBackpic:     INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
AbsolFrontpic:   INCBIN "gfx/pokemon/absol/front.animated.2bpp.lz"


SECTION "Pics 14", ROMX

TrumbeakBackpic:    INCBIN "gfx/pokemon/trumbeak/back.2bpp.lz"
FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
YamaskFrontpic:     INCBIN "gfx/pokemon/yamask/front.animated.2bpp.lz"
TogeticBackpic:      INCBIN "gfx/pokemon/togetic/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
GeodudeBackpic:      INCBIN "gfx/pokemon/geodude/back.2bpp.lz"
ScytherBackpic:      INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
VileplumeBackpic:    INCBIN "gfx/pokemon/vileplume/back.2bpp.lz"
HitmonchanBackpic:   INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"
RioluBackpic:     INCBIN "gfx/pokemon/riolu/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
FlygonBackpic:       INCBIN "gfx/pokemon/flygon/back.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
TyrogueBackpic:      INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
GeodudeFrontpic:     INCBIN "gfx/pokemon/geodude/front.animated.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
HelioliskBackpic:    INCBIN "gfx/pokemon/heliolisk/back.2bpp.lz"
SealeoBackpic:     INCBIN "gfx/pokemon/sealeo/back.2bpp.lz"
WalreinBackpic:     INCBIN "gfx/pokemon/walrein/back.2bpp.lz"
SalamenceBackpic:    INCBIN "gfx/pokemon/salamence/back.2bpp.lz"
KadabraBackpic:      INCBIN "gfx/pokemon/kadabra/back.2bpp.lz"
SimisearBackpic:     INCBIN "gfx/pokemon/simisear/back.2bpp.lz"
CofagrigusBackpic:       INCBIN "gfx/pokemon/cofagrigus/back.2bpp.lz"
VibravaBackpic:      INCBIN "gfx/pokemon/vibrava/back.2bpp.lz"
MagnezoneBackpic:    INCBIN "gfx/pokemon/magnezone/back.2bpp.lz"
IgglybuffFrontpic:   INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
LinooneBackpic:      INCBIN "gfx/pokemon/linoone/back.2bpp.lz"
VulpixBackpic:       INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
EkansBackpic:        INCBIN "gfx/pokemon/ekans/back.2bpp.lz"
CameruptBackpic:      INCBIN "gfx/pokemon/camerupt/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
PansageBackpic:      INCBIN "gfx/pokemon/pansage/back.2bpp.lz"
PikachuBackpic:      INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
SkittyBackpic:     INCBIN "gfx/pokemon/skitty/back.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
AegislashBackpic:      INCBIN "gfx/pokemon/aegislash/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
ShuppetFrontpic:      INCBIN "gfx/pokemon/shuppet/front.animated.2bpp.lz"
NoibatBackpic:       INCBIN "gfx/pokemon/noibat/back.2bpp.lz"
SpoinkBackpic:       INCBIN "gfx/pokemon/spoink/back.2bpp.lz"
BellossomBackpic:    INCBIN "gfx/pokemon/bellossom/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
BaltoyBackpic:       INCBIN "gfx/pokemon/baltoy/back.2bpp.lz"


SECTION "Pics 15", ROMX

GlaceonBackpic:       INCBIN "gfx/pokemon/glaceon/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
DiglettFrontpic:     INCBIN "gfx/pokemon/diglett/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
MukBackpic:          INCBIN "gfx/pokemon/muk/back.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
AurorusBackpic:      INCBIN "gfx/pokemon/aurorus/back.2bpp.lz"
HonedgeBackpic:      INCBIN "gfx/pokemon/honedge/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
MetangBackpic:       INCBIN "gfx/pokemon/metang/back.2bpp.lz"
SlowbroBackpic:      INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
SimisageBackpic:     INCBIN "gfx/pokemon/simisage/back.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
ZapdosBackpic:        INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
WailmerFrontpic:      INCBIN "gfx/pokemon/wailmer/front.animated.2bpp.lz"
StaraptorBackpic:    INCBIN "gfx/pokemon/staraptor/back.2bpp.lz"
LampentBackpic:         INCBIN "gfx/pokemon/lampent/back.2bpp.lz"
PoliwhirlBackpic:    INCBIN "gfx/pokemon/poliwhirl/back.2bpp.lz"
LeafeonBackpic:          INCBIN "gfx/pokemon/leafeon/back.2bpp.lz"
GoomyBackpic:        INCBIN "gfx/pokemon/goomy/back.2bpp.lz"
AbraBackpic:         INCBIN "gfx/pokemon/abra/back.2bpp.lz"
SylveonBackpic:   INCBIN "gfx/pokemon/sylveon/back.2bpp.lz"
KakunaFrontpic:      INCBIN "gfx/pokemon/kakuna/front.animated.2bpp.lz"
DugtrioBackpic:      INCBIN "gfx/pokemon/dugtrio/back.2bpp.lz"
LuxrayBackpic:       INCBIN "gfx/pokemon/luxray/back.2bpp.lz"
NidoranFBackpic:     INCBIN "gfx/pokemon/nidoran_f/back.2bpp.lz"
GravelerBackpic:     INCBIN "gfx/pokemon/graveler/back.2bpp.lz"
LucarioBackpic:        INCBIN "gfx/pokemon/lucario/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
WeedleFrontpic:      INCBIN "gfx/pokemon/weedle/front.animated.2bpp.lz"
OshawottBackpic:     INCBIN "gfx/pokemon/oshawott/back.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pokemon/pangoro/back.2bpp.lz"
MismagiusBackpic:    INCBIN "gfx/pokemon/mismagius/back.2bpp.lz"
GengarBackpic:       INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
ZigzagoonBackpic:    INCBIN "gfx/pokemon/zigzagoon/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"


SECTION "Pics 16", ROMX

PhantumpBackpic:     INCBIN "gfx/pokemon/phantump/back.2bpp.lz"
TrevenantBackpic:      INCBIN "gfx/pokemon/trevenant/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
LuxioBackpic:        INCBIN "gfx/pokemon/luxio/back.2bpp.lz"
PanpourBackpic:      INCBIN "gfx/pokemon/panpour/back.2bpp.lz"
DecidueyeBackpic:     INCBIN "gfx/pokemon/decidueye/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
AzurillBackpic:    INCBIN "gfx/pokemon/azurill/back.2bpp.lz"
TogepiFrontpic:      INCBIN "gfx/pokemon/togepi/front.animated.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
AltariaBackpic:         INCBIN "gfx/pokemon/altaria/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
SphealBackpic:     INCBIN "gfx/pokemon/spheal/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
LitleoBackpic:       INCBIN "gfx/pokemon/litleo/back.2bpp.lz"
MetapodFrontpic:     INCBIN "gfx/pokemon/metapod/front.animated.2bpp.lz"
SeelBackpic:         INCBIN "gfx/pokemon/seel/back.2bpp.lz"
BanetteBackpic:     INCBIN "gfx/pokemon/banette/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
CaterpieFrontpic:    INCBIN "gfx/pokemon/caterpie/front.animated.2bpp.lz"
MakuhitaBackpic:       INCBIN "gfx/pokemon/makuhita/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
GranbullBackpic:     INCBIN "gfx/pokemon/shroomish/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
JoltikBackpic:       INCBIN "gfx/pokemon/joltik/back.2bpp.lz"
LotadBackpic:      INCBIN "gfx/pokemon/lotad/back.2bpp.lz"
LaprasBackpic:       INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
KyogreBackpic:       INCBIN "gfx/pokemon/kyogre/back.2bpp.lz"
RowletBackpic:    INCBIN "gfx/pokemon/rowlet/back.2bpp.lz"
CorsolaBackpic:      INCBIN "gfx/pokemon/corsola/back.2bpp.lz"


SECTION "Pics 17", ROMX

MedititeBackpic:     INCBIN "gfx/pokemon/meditite/back.2bpp.lz"
VaporeonBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
TentacoolBackpic:    INCBIN "gfx/pokemon/tentacool/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
SmoochumBackpic:     INCBIN "gfx/pokemon/smoochum/back.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
ShinxBackpic:        INCBIN "gfx/pokemon/shinx/back.2bpp.lz"
GrimerBackpic:       INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
RoseradeBackpic:      INCBIN "gfx/pokemon/roserade/back.2bpp.lz"
StaraviaBackpic:     INCBIN "gfx/pokemon/staravia/back.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
MimikyuBackpic:       INCBIN "gfx/pokemon/mimikyu/back.2bpp.lz"
CaterpieBackpic:     INCBIN "gfx/pokemon/caterpie/back.2bpp.lz"
TogekissFrontpic:    INCBIN "gfx/pokemon/togekiss/front.animated.2bpp.lz"
LitwickBackpic:        INCBIN "gfx/pokemon/litwick/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
ArbokBackpic:        INCBIN "gfx/pokemon/arbok/back.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
DragoniteBackpic:    INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
HitmonleeBackpic:    INCBIN "gfx/pokemon/hitmonlee/back.2bpp.lz"
SwabluFrontpic:        INCBIN "gfx/pokemon/swablu/front.animated.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
TeddiursaBackpic:    INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
KakunaBackpic:       INCBIN "gfx/pokemon/kakuna/back.2bpp.lz"
HelioptileBackpic:    INCBIN "gfx/pokemon/helioptile/back.2bpp.lz"
TogepiBackpic:       INCBIN "gfx/pokemon/togepi/back.2bpp.lz"
BudewBackpic:       INCBIN "gfx/pokemon/budew/back.2bpp.lz"
EmolgaBackpic:      INCBIN "gfx/pokemon/emolga/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
IgglybuffBackpic:    INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
DelcattyBackpic:    INCBIN "gfx/pokemon/delcatty/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
WailmerBackpic:       INCBIN "gfx/pokemon/wailmer/back.2bpp.lz"
YamaskBackpic:      INCBIN "gfx/pokemon/yamask/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
WigglytuffBackpic:   INCBIN "gfx/pokemon/wigglytuff/back.2bpp.lz"
GroudonBackpic:     INCBIN "gfx/pokemon/groudon/back.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
WeedleBackpic:       INCBIN "gfx/pokemon/weedle/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
PikipekBackpic:       INCBIN "gfx/pokemon/pikipek/back.2bpp.lz"
MagmortorBackpic:    INCBIN "gfx/pokemon/magmortor/back.2bpp.lz"
GastlyBackpic:       INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
GalvantulaBackpic:   INCBIN "gfx/pokemon/galvantula/back.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"



SECTION "Pics 18", ROMX

AmauraBackpic:     INCBIN "gfx/pokemon/amaura/back.2bpp.lz"
ArticunoBackpic:       INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
PoliwagBackpic:      INCBIN "gfx/pokemon/poliwag/back.2bpp.lz"
TrapinchBackpic:     INCBIN "gfx/pokemon/trapinch/back.2bpp.lz"
ToucannonBackpic:      INCBIN "gfx/pokemon/toucannon/back.2bpp.lz"
DewgongBackpic:      INCBIN "gfx/pokemon/dewgong/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
SlowpokeBackpic:     INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
BronzorBackpic:    INCBIN "gfx/pokemon/bronzor/back.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
ShuppetBackpic:       INCBIN "gfx/pokemon/shuppet/back.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
TropiusBackpic:      INCBIN "gfx/pokemon/tropius/back.2bpp.lz"
TogekissBackpic:     INCBIN "gfx/pokemon/togekiss/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
DoubladeBackpic:      INCBIN "gfx/pokemon/doublade/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
ClaydolBackpic:    INCBIN "gfx/pokemon/claydol/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
SwabluBackpic:         INCBIN "gfx/pokemon/swablu/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
GolemBackpic:        INCBIN "gfx/pokemon/golem/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
DiglettBackpic:      INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
JynxBackpic:         INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
MightyenaBackpic:    INCBIN "gfx/pokemon/mightyena/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
PyroarBackpic:   INCBIN "gfx/pokemon/pyroar/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


SECTION "Pics 19", ROMX

ChandelureFrontPic:  INCBIN "gfx/pokemon/chandelure/front.2bpp.lz"
ChandelureBackPic:   INCBIN "gfx/pokemon/chandelure/back.2bpp.lz"
MunchlaxFrontPic:    INCBIN "gfx/pokemon/munchlax/front.2bpp.lz"
MunchlaxBackPic:     INCBIN "gfx/pokemon/munchlax/back.2bpp.lz"
BeldumBackpic:       INCBIN "gfx/pokemon/beldum/back.2bpp.lz"
BagonBackpic:        INCBIN "gfx/pokemon/bagon/back.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
BaltoyFrontpic:      INCBIN "gfx/pokemon/baltoy/front.animated.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
MawileBackpic:      INCBIN "gfx/pokemon/mawile/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"
BossPic: 			 INCBIN "gfx/trainers/boss.2bpp.lz"
TyrantrumBackpic:      INCBIN "gfx/pokemon/tyrantrum/back.2bpp.lz"
RoseliaBackpic:     INCBIN "gfx/pokemon/roselia/back.2bpp.lz"
HonchkrowBackpic:    INCBIN "gfx/pokemon/honchkrow/back.2bpp.lz"
HariyamaBackpic:     INCBIN "gfx/pokemon/hariyama/back.2bpp.lz"
AmauraFrontpic:    INCBIN "gfx/pokemon/amaura/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
AbsolBackpic:    INCBIN "gfx/pokemon/absol/back.2bpp.lz"
SkarmoryBackpic:     INCBIN "gfx/pokemon/skarmory/back.2bpp.lz"
MetapodBackpic:      INCBIN "gfx/pokemon/metapod/back.2bpp.lz"
JigglypuffBackpic:   INCBIN "gfx/pokemon/jigglypuff/back.2bpp.lz"
OddishBackpic:       INCBIN "gfx/pokemon/oddish/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"
CoachMPic:			 INCBIN "gfx/trainers/coach_m.2bpp.lz"
CoachFPic:			 INCBIN "gfx/trainers/coach_f.2bpp.lz"

; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX

SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
